language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '10'
  - '8'


after_success:
  - yarn travis-deploy-once "yarn semantic-release"

before_deploy:
  - yarn build-storybook

deploy:
  provider: surge
  project: ./storybook-static/
  domain: react-video-recorder.surge.sh
  skip_cleanup: true
  on:
    branch: master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
